### ISSUE TITLE
Add ‘next lesson’ / ‘previous lesson’ button for easier navigation 

### ISSUE THREAD

**Issue by kirlosik** [sj50179/Google-Data-Analytics-Professional-Certificate#2]
Hi Brenden @brendensong, I’m also fascinated by data!

Thanks a lot for creating such an amazing content! It helps a lot to refresh the material.

May I kindly ask you to add ‘next lesson’ / ‘previous lesson’ buttons so that it would be easier to go back and forth between the lessons?

<details>
  <summary>Click to view attached image!</summary>
  
 ![EB3B6F6D-FEA2-4FBD-ACE2-975DA6E03B3C](https://user-images.githubusercontent.com/97167558/148232173-e63f8d21-1db5-4efa-9478-dfc5e0fd3472.jpeg)
</details>

//

I would love to create a small group of 5 people or so, in which we would be inspiring each other, exchanging useful materials, brainstorming and helping to solve the problems faster.

I heard that study groups help to learn faster and more effectively. And I would be happy if we would start such group together with you.

//

I got enrolled into Business Analytics Scholarship program from Udacity & Bertelsmann and keep learning Data Analytics.

You can find me by searching for ‘Kirill Losik’ in google
Dropping a message in <ins>Telegram</ins> would be best <ins>http://t.me/kirlosik</ins>

Love  💛

<details>
  <summary>Click to view attached images!</summary>
  

![B03A30C4-7D2C-433A-B68B-B9344971200E](https://user-images.githubusercontent.com/97167558/148232246-bf9c804f-2944-401b-9835-ccbb83ef0607.jpeg)
![B4D1887E-0061-4DDE-82AF-AC1D7BE0D872](https://user-images.githubusercontent.com/97167558/148232271-c264f6b5-9cac-4a47-80be-ad5ab1ae6989.png)

</details>

**Comment by sj50179** [comment]
First of all, I apologize for the late response, and I'm currently pursuing a career as a front-end web developer rather than data analytics, so while I appreciate the invitation, I don't think it's a good fit for me.

And about the navigation buttons, first of all, I don't think I can add them to the GitHub wiki article titles arbitrarily, and I don't think I can do it because I have too many pages and it would be too much work to add them to each page.

I apologize for the unhelpful answer. Have a nice day!
