### ISSUE TITLE
1.4.4.Introducing Qwiklabs was removed from the course

### ISSUE THREAD

**Issue by kirlosik** [sj50179/Google-Data-Analytics-Professional-Certificate#3]
Hi, probably they shifted Qwiklabs to another part of the course
![3745290A-C5BA-4F38-9240-CA7236A0C109](https://user-images.githubusercontent.com/97167558/148241859-d08a947a-0710-4eb6-8a23-b22749705d35.png)
![C2196B0A-DF51-4BEE-BBD2-69FE5F23A469](https://user-images.githubusercontent.com/97167558/148241870-52d5084a-77e3-4a33-b6d6-a173e95cf67f.png)
![E2A5F362-95DB-4CA3-9187-AB013EE5651D](https://user-images.githubusercontent.com/97167558/148241875-f08befb5-0c82-458d-81e9-8f34a5819d1f.png)

**Comment by sj50179** [comment]
First of all, I apologize for the delay in responding. 

I don't have access to the coursera link at the moment, so I can't check or correct what you're referring to. There may have been updates since I finished the course.

I apologize for the unhelpful response. I wish you the best of luck in all your career endeavors.
